name: Update AlphaSSL Certificates

on:
  schedule:
    - cron: '0 0 * * *'  # UTC saatine göre her gün saat 00:00'da çalışır
  workflow_dispatch: # Manuel tetikleme imkanı sağlar

jobs:
  update-certificates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Unzip
        run: sudo apt-get install -y unzip

      - name: Download and Extract Certificates
        run: |
          mkdir -p certificates
          CERT_ZIP_URLS=(
            "https://www.ssl2buy.com/wp-content/uploads/2024/01/alphasslrootcabundle-r6.zip"
            "https://www.ssl2buy.com/wp-content/uploads/2022/12/alphasslrootcabundle-g4.zip"
            # Gelecekte daha fazla URL ekleyebilirsiniz
          )
          for url in "${CERT_ZIP_URLS[@]}"; do
            echo "Downloading $url..."
            filename=$(basename "$url")
            curl -sSL "$url" -o "$filename"
            echo "Extracting $filename..."
            unzip -o "$filename" -d certificates/
            # İndirilen .zip dosyasını silmek isterseniz aşağıdaki satırı aktif edebilirsiniz
            rm "$filename"
          done

      - name: Check for Changes
        id: git-check
        run: |
          git add certificates
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit Changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git commit -m "Update AlphaSSL certificates [skip ci]"

      - name: Push Changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
