name: Update AlphaSSL Certificates

on:
  schedule:
    - cron: '0 0 * * *'  # UTC saatine göre her gün saat 00:00'da çalışır
  workflow_dispatch: # Manuel tetikleme imkanı sağlar

permissions:
  contents: write  # Push işlemi için gerekli izinleri tanımlar

jobs:
  update-certificates:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip curl

      - name: Download and Extract Certificates
        run: |
          mkdir -p certificates
          # Ana sayfayı indir
          curl -sSL https://www.ssl2buy.com/wiki/alphassl-ca-bundle -o main_page.html

          # main_page.html içeriğini loglamak için ekleme
          echo "### main_page.html Content ###"
          head -n 50 main_page.html  # İlk 50 satırı gösterir, gerektiğinde artırabilirsiniz
          echo "### End of main_page.html Content ###"

          # .zip dosyalarının URL'lerini çıkart
          ZIP_URLS=$(grep -oP 'https://www.ssl2buy.com/wp-content/uploads/[0-9]{4}/[0-9]{2}/alphasslrootcabundle-[a-z0-9]+\.zip' main_page.html | sort | uniq)
          echo "Found ZIP URLs:"
          echo "$ZIP_URLS"

          # ZIP URL'leri bulunamadıysa workflow'u durdur
          if [ -z "$ZIP_URLS" ]; then
            echo "No ZIP URLs found. Exiting."
            exit 1
          fi

          # Her bir .zip dosyasını indirip aç
          for url in $ZIP_URLS; do
            echo "Downloading $url..."
            filename=$(basename "$url")
            curl -sSL "$url" -o "$filename"
            echo "Extracting $filename..."
            unzip -o "$filename" -d certificates/
            # İndirilen .zip dosyasını silmek isterseniz aşağıdaki satırı aktif edebilirsiniz
            rm "$filename"
          done

          # Ana sayfa dosyasını sil
          rm main_page.html

      - name: List Certificates Directory
        run: |
          echo "Listing certificates directory:"
          ls -la certificates

      - name: Validate Certificates
        run: |
          FILE_COUNT=$(ls -1 certificates | wc -l)
          echo "Number of files in certificates directory: $FILE_COUNT"
          if [ "$FILE_COUNT" -eq 0 ]; then
            echo "No certificate files found. Exiting."
            exit 1
          fi

      - name: Check for Changes
        id: git-check
        run: |
          git add certificates
          if git diff --cached --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit Changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git commit -m "Update AlphaSSL certificates [skip ci]"

      - name: Push Changes
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git push origin HEAD:${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
